<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../build/Timberborn.Managed.props" />

  <ItemGroup>
    <ProjectReference Include="..\Wildfire.Core\Wildfire.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Bindito.Core">
      <HintPath>$(TimberbornManagedPath)/Bindito.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.EntityPanelSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.EntityPanelSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Localization">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Localization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.SingletonSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.SingletonSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.SettingsSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.SettingsSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.StatusSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.StatusSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.BlueprintSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.BlueprintSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.MapStateSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.MapStateSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Persistence">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Persistence.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.WorldPersistence">
      <HintPath>$(TimberbornManagedPath)/Timberborn.WorldPersistence.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.TimeSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.TimeSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.MapIndexSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.MapIndexSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.BlockSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.BlockSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Buildings">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Buildings.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Navigation">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Navigation.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.BehaviorSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.BehaviorSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Carrying">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Carrying.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Yielding">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Yielding.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Gathering">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Gathering.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Growing">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Growing.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Cutting">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Cutting.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Forestry">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Forestry.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.NaturalResourcesLifecycle">
      <HintPath>$(TimberbornManagedPath)/Timberborn.NaturalResourcesLifecycle.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.NaturalResourcesMoisture">
      <HintPath>$(TimberbornManagedPath)/Timberborn.NaturalResourcesMoisture.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.NaturalResourcesModelSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.NaturalResourcesModelSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.EntitySystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.EntitySystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Common">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Stockpiles">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Stockpiles.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.SimpleOutputBuildings">
      <HintPath>$(TimberbornManagedPath)/Timberborn.SimpleOutputBuildings.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.InventorySystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.InventorySystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Goods">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Goods.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.GoodStackSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.GoodStackSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.ConstructionSites">
      <HintPath>$(TimberbornManagedPath)/Timberborn.ConstructionSites.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Explosions">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Explosions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.AutomationBuildings">
      <HintPath>$(TimberbornManagedPath)/Timberborn.AutomationBuildings.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.TickSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.TickSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.QuickNotificationSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.QuickNotificationSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.CameraSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.CameraSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Coordinates">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Coordinates.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.TemplateSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.TemplateSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.TemplateInstantiation">
      <HintPath>$(TimberbornManagedPath)/Timberborn.TemplateInstantiation.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.WalkingSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.WalkingSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.WorkSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.WorkSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.EnterableSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.EnterableSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.InputSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.AreaSelectionSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.AreaSelectionSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.AreaSelectionSystemUI">
      <HintPath>$(TimberbornManagedPath)/Timberborn.AreaSelectionSystemUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.BlockObjectPickingSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.BlockObjectPickingSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.BottomBarSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.BottomBarSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.ToolButtonSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.ToolButtonSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.ToolSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.ToolSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.ToolSystemUI">
      <HintPath>$(TimberbornManagedPath)/Timberborn.ToolSystemUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.UILayoutSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.UILayoutSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.BaseComponentSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.BaseComponentSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.Beavers">
      <HintPath>$(TimberbornManagedPath)/Timberborn.Beavers.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.SelectionSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.SelectionSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.TerrainSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.TerrainSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.TerrainPhysics">
      <HintPath>$(TimberbornManagedPath)/Timberborn.TerrainPhysics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.SoilMoistureSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.SoilMoistureSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.SoilContaminationSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.SoilContaminationSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Timberborn.WindSystem">
      <HintPath>$(TimberbornManagedPath)/Timberborn.WindSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.MathematicsModule">
      <HintPath>$(TimberbornManagedPath)/UnityEngine.MathematicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(TimberbornManagedPath)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(TimberbornManagedPath)/UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(TimberbornManagedPath)/UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(TimberbornManagedPath)/UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>$(TimberbornManagedPath)/UnityEngine.UIElementsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Timberborn.GameDistricts"><HintPath>$(TimberbornManagedPath)/Timberborn.GameDistricts.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.ResourceCountingSystem"><HintPath>$(TimberbornManagedPath)/Timberborn.ResourceCountingSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.CharacterMovementSystem"><HintPath>$(TimberbornManagedPath)/Timberborn.CharacterMovementSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.CharacterNavigation"><HintPath>$(TimberbornManagedPath)/Timberborn.CharacterNavigation.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.NeedSystem"><HintPath>$(TimberbornManagedPath)/Timberborn.NeedSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.CharacterControlSystem"><HintPath>$(TimberbornManagedPath)/Timberborn.CharacterControlSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.Characters"><HintPath>$(TimberbornManagedPath)/Timberborn.Characters.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.MortalSystem"><HintPath>$(TimberbornManagedPath)/Timberborn.MortalSystem.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Timberborn.AssetSystem"><HintPath>$(TimberbornManagedPath)/Timberborn.AssetSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.Timbermesh"><HintPath>$(TimberbornManagedPath)/Timberborn.Timbermesh.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Timberborn.DuplicationSystem"><HintPath>$(TimberbornManagedPath)/Timberborn.DuplicationSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Timberborn.RelationSystem"><HintPath>$(TimberbornManagedPath)/Timberborn.RelationSystem.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Blueprints\**\*.blueprint.json" />
    <EmbeddedResource Include="Assets\WildfireAshOverlay4096.png" />
    <EmbeddedResource Include="Assets\WildfireAshGround2048.png" />
    <EmbeddedResource Include="Assets\WildfireAshMask2048Levels.png" />
    <EmbeddedResource Include="Assets\WildfireAshMask4096Levels.png" />
    <EmbeddedResource Include="Assets\WildfireIgniteToolIcon.png" />
    <EmbeddedResource Include="Assets\WildfireFertilizeToolIcon.png" />
    <EmbeddedResource Include="Assets\WildfireIgniteToolCursorLarge.png" />
    <EmbeddedResource Include="Assets\WildfireIgniteToolCursorSmall.png" />
  </ItemGroup>

</Project>
