namespace Wildfire.Timberborn.Tests;

public sealed class NativeWaterRemovalTaskTests
{
    [Theory]
    [InlineData(1f, 0f, false, .2f, 0f, .8f)]
    [InlineData(.1f, 0f, false, .1f, 0f, 0f)]
    [InlineData(0f, 0f, false, 0f, 0f, 0f)]
    [InlineData(1f, .5f, false, .2f, 0f, .8f)]
    [InlineData(1f, 1f, false, 0f, 0f, 1f)]
    [InlineData(1f, .5f, true, 0f, .2f, .8f)]
    public void ActualTaskProducesPhysicalGradeReceiptsAndClearsCompletedBatch(
        float initial, float contamination, bool dirty, float expectedClean, float expectedDirty, float final)
    {
        using var f = new NativeWaterRemovalTaskFixture(initial, contamination);
        f.Remove(.2f, dirty);
        Assert.Equal(0, f.ReceiptCount);
        var receipt = f.Complete();
        Near(expectedClean, receipt.Clean);
        Near(expectedDirty, receipt.Dirty);
        Near(final, f.Depth + f.Overflow);
        Near(initial, f.Depth + f.Overflow + receipt.Clean + receipt.Dirty);
        Assert.Equal(1, f.ReceiptCount); // Dry valid columns still get an actual zero-valued entry.
        f.Complete();
        Assert.Equal(0, f.ReceiptCount);
        Near(final, f.Depth + f.Overflow);
    }

    [Fact]
    public void OrderedSameCoordinateRequestsAccumulateActualReceipt()
    {
        using var f = new NativeWaterRemovalTaskFixture();
        f.Remove(.2f);
        f.Remove(.2f);
        var receipt = f.Complete();
        Near(.4f, receipt.Clean);
        Assert.Equal(0, receipt.Dirty);
        Assert.Equal(1, f.ReceiptCount);
        Near(.6f, f.Depth);
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void OutsideColumnProducesNoReceipt(bool ceiling)
    {
        using var f = new NativeWaterRemovalTaskFixture();
        int z = ceiling ? f.Top : 3;
        f.Remove(.2f, z: z);
        Assert.Equal((0f, 0f), f.Complete(z));
        Assert.Equal(0, f.ReceiptCount);
        Assert.Equal(1, f.Depth);
    }

    [Fact]
    public void NativeVerticalStrideSelectsUpperColumnWithoutChangingLower()
    {
        using var f = new NativeWaterRemovalTaskFixture(secondColumn: true);
        f.Remove(.2f);
        Near(.2f, f.Complete().Clean);
        Near(.8f, f.Depth);
        Assert.Equal(2, f.LowerDepth);
    }

    [Theory]
    [InlineData(0f)]
    [InlineData(.5f)]
    public void PressureReceiptUsesActualPhysicalGradesRatherThanRequestedGrade(float contamination)
    {
        using var f = new NativeWaterRemovalTaskFixture(1, contamination, .5f, ceiling: 5);
        Assert.Equal(8, f.Pressure); // Installed native simulator parameter, not a fixture tuning choice.
        f.Remove(.2f);
        var receipt = f.Complete();
        Near(1.3f, f.Depth + f.Overflow);
        Near(.2f, receipt.Clean + receipt.Dirty);
        if (contamination == 0)
        {
            Near(.2f, receipt.Clean);
            Assert.Equal(0, receipt.Dirty);
        }
        else
        {
            Near(.12708333f, receipt.Clean);
            Near(.07291667f, receipt.Dirty);
            Near(2.5f / 4.8f, f.Contamination);
        }
    }

    [Fact]
    public void FullQuantumRetryUsesRealCreditAndPreservesSavedSurplusWithoutEpsilonAdmission()
    {
        using var f = new NativeWaterRemovalTaskFixture();
        var s = f.Shore;
        var bucket = s.Bucket();
        Assert.Equal(.2f, s.BucketVolume); // Actual Water-good converter.
        Assert.Equal(0, f.Demand(s.BucketVolume));
        var first = f.Complete();
        s.CreditNativeInputs(); // Actual native service reads the dictionary generated by Run.
        Assert.Equal(first.Clean, s.Buffer(s.Source));
        Assert.True(s.Buffer(s.Source) < s.BucketVolume);
        float deficit = s.BucketVolume - s.Buffer(s.Source);
        f.Demand(deficit);
        Assert.Equal(0, s.PendingRequests); // Native multiplier suppresses deficit-only demand.
        f.Remove(deficit);
        Assert.Equal((0f, 0f), f.Complete()); // Direct sub-resolution request also removes nothing.
        Assert.False(s.TryFill(s.Source, bucket)); // Queues a full demand; exact admission remains false.
        Assert.Equal(0, s.Stock(bucket));
        f.Complete();
        s.CreditNativeInputs();
        Assert.True(s.TryFill(s.Source, bucket));
        Assert.Equal(1, s.Stock(bucket));
        Assert.True(s.Buffer(s.Source) > 0);
        Assert.Equal(s.Buffer(s.Source), s.Buffer(s.SaveLoadInput(s.Source)));
        Near(1, f.Depth + f.Overflow + s.Buffer(s.Source) + s.BucketVolume);
        // TryFill may prefetch another quantum; that unexecuted queue is not credited or counted as cargo.
    }

    private static void Near(float expected, float actual) => Assert.InRange(actual, expected - .000005f, expected + .000005f);
}
