<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Wildfire.Core/Wildfire.Core.csproj" />
    <ProjectReference Include="../../src/Wildfire.Timberborn/Wildfire.Timberborn.csproj" />
    <ProjectReference Include="../../src/Wildfire.Unity/Wildfire.Unity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Timberborn.SettingsSystem">
      <HintPath>$(HOME)/Library/Application Support/Steam/steamapps/common/Timberborn/Timberborn.app/Contents/Resources/Data/Managed/Timberborn.SettingsSystem.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
