#!/usr/bin/env bun

import { existsSync, lstatSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "fs";
import { dirname, join, relative, resolve } from "path";
import { deflateRawSync, inflateRawSync } from "node:zlib";
import { lookupMaterialProfile, type MaterialClass, type MaterialFieldProfile } from "./material-field-schema";

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
type JsonObject = { [key: string]: JsonValue };

type Options = {
  allowUserSaveOutput: boolean;
  dryRun: boolean;
  help: boolean;
  mutateEntities: boolean;
  name: string;
  outputDir: string;
  overwrite: boolean;
  templatePath: string | null;
};

type ZipEntry = {
  compressedSize: number;
  compressionMethod: number;
  data: Buffer;
  name: string;
  uncompressedSize: number;
};

type Coordinate = {
  x: number;
  y: number;
  z: number;
};

type EntityRequest = {
  category: string;
  coordinate: Coordinate;
  template: string;
};

type EntityPlacement = EntityRequest & {
  blockedReason: string | null;
};

type ScenarioCheckpoint = {
  category: string;
  companionField: {
    ashQuality: string;
    burnCapacity: number;
    contaminationBehavior: string;
    consequenceTargetKind: string;
    resourcePolicy: string;
  };
  coordinate: Coordinate;
  expectedCellMaterialClass: MaterialClass;
  expectedPackedCellBand: {
    flammability: number;
    fuel: number;
    heatLoss: number;
    terrain: number;
    water: number;
  };
  expectedSourceMaterialClass: MaterialClass;
  id: string;
  template: string | null;
};

type ArchiveInspection = {
  entries: ZipEntry[];
  jsonFiles: Record<string, JsonValue>;
};

type Manifest = {
  generatedAt: string;
  generator: {
    command: string;
    mutateEntities: boolean;
    name: string;
    tool: string;
    version: string;
  };
  output: {
    archivePath: string;
    manifestPath: string;
  };
  plan: {
    expectedEntityCountsByCategory: Record<string, number>;
    layout: {
      baseHeight: number;
      region: string;
      size: { x: number; y: number };
      xBands: string[];
    };
  };
  result: {
    blockedPlacements: EntityPlacement[];
    evidence: {
      badwaterFlow: string;
      storageInventory: string;
      waterFlow: string;
    };
    fieldCheckpoints: ScenarioCheckpoint[];
    generatedEntityCountsByCategory: Record<string, number>;
    generatedEntities: EntityRequest[];
    schemaBlockers: string[];
  };
  template: {
    entries: string[];
    jsonFiles: string[];
    mapSize: { x: number | null; y: number | null };
    path: string;
    version: string | null;
  };
  validationTargets: string[];
};

const usage = `Usage:
  bun scripts/generate-wildfire-scenario-save.ts --template <path.timber> [options]

Options:
  --template <path>              Known-good .timber save/map archive to inspect and copy.
  --output-dir <path>            Output folder. Default: Timberborn WildfireQA/generated-scenarios/<name>-<timestamp>.
  --name <slug>                  Output archive basename. Default: wildfire-world-consequence-scenario.
  --dry-run                      Inspect, plan, and print manifest summary without writing files.
  --overwrite                    Allow replacing an existing output folder only when its manifest marker was generated by this tool.
  --no-entity-mutation           Copy the template archive unchanged and write manifest blockers only.
  --allow-user-save-output       Compatibility flag; save-root writes are still refused.
  --help                         Show this help.

Examples:
  bun scripts/generate-wildfire-scenario-save.ts --template "$HOME/Documents/Timberborn/ExperimentalSaves/Wildfire testing/Wildfire testing.timber" --dry-run
  bun scripts/generate-wildfire-scenario-save.ts --template ./template-copy.timber --output-dir "$HOME/Library/Application Support/Mechanistry/Timberborn/WildfireQA/generated-scenarios/twf-118-check"
`;

const home = process.env.HOME ?? "";
const defaultQaRoot = join(home, "Library", "Application Support", "Mechanistry", "Timberborn", "WildfireQA");
const generatedScenariosRoot = join(defaultQaRoot, "generated-scenarios");
const generatorVersion = "TWF-132.0";
const generatorTool = "wildfire-scenario-save-generator";
const manifestFileName = "wildfire-scenario-manifest.json";
const timberbornSaveTimestampPattern = /^\d{2}\/\d{2}\/\d{4} \d{2}:\d{2}:\d{2}$/u;

const log = (message: string): void => {
  console.log(`[wildfire-scenario-save] ${message}`);
};

const fail = (message: string): never => {
  throw new Error(`[wildfire-scenario-save] ${message}`);
};

const requireValue = (args: string[], index: number, flag: string): string => {
  const value = args[index];
  if (!value || value.startsWith("--")) {
    fail(`${flag} requires a value.`);
  }

  return value;
};

const timestampSlug = (date: Date): string => date.toISOString().replace(/[:.]/gu, "-");

const defaultOutputDir = (name: string): string => join(generatedScenariosRoot, `${name}-${timestampSlug(new Date())}`);

const validateSlug = (name: string): string => {
  if (!/^[a-z0-9][a-z0-9-]{0,79}$/u.test(name)) {
    fail(`Invalid --name "${name}". Use a lowercase slug with only a-z, 0-9, and hyphen, starting with a letter or number.`);
  }

  return name;
};

const parseArgs = (args: string[]): Options => {
  const options: Options = {
    allowUserSaveOutput: false,
    dryRun: false,
    help: false,
    mutateEntities: true,
    name: "wildfire-world-consequence-scenario",
    outputDir: "",
    overwrite: false,
    templatePath: null,
  };
  let skipNext = false;

  args.reduce((_, arg, index) => {
    if (skipNext) {
      skipNext = false;
      return undefined;
    }

    if (arg === "--allow-user-save-output") {
      options.allowUserSaveOutput = true;
    } else if (arg === "--dry-run") {
      options.dryRun = true;
    } else if (arg === "--help" || arg === "-h") {
      options.help = true;
    } else if (arg === "--name") {
      options.name = requireValue(args, index + 1, arg);
      skipNext = true;
    } else if (arg.startsWith("--name=")) {
      options.name = arg.slice("--name=".length);
    } else if (arg === "--no-entity-mutation") {
      options.mutateEntities = false;
    } else if (arg === "--output-dir") {
      options.outputDir = resolve(requireValue(args, index + 1, arg));
      skipNext = true;
    } else if (arg.startsWith("--output-dir=")) {
      options.outputDir = resolve(arg.slice("--output-dir=".length));
    } else if (arg === "--overwrite") {
      options.overwrite = true;
    } else if (arg === "--template") {
      options.templatePath = resolve(requireValue(args, index + 1, arg));
      skipNext = true;
    } else if (arg.startsWith("--template=")) {
      options.templatePath = resolve(arg.slice("--template=".length));
    } else {
      fail(`Unknown argument: ${arg}`);
    }

    return undefined;
  }, undefined);

  options.name = validateSlug(options.name);
  options.outputDir = resolve(options.outputDir === "" ? defaultOutputDir(options.name) : options.outputDir);

  return options;
};

const asObject = (value: JsonValue | undefined): JsonObject | null =>
  value !== null && typeof value === "object" && !Array.isArray(value) ? value : null;

const asArray = (value: JsonValue | undefined): JsonValue[] | null => (Array.isArray(value) ? value : null);

const asNumber = (value: JsonValue | undefined): number | null => (typeof value === "number" ? value : null);

const asString = (value: JsonValue | undefined): string | null => (typeof value === "string" ? value : null);

const cloneJson = <T extends JsonValue>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

const twoDigit = (value: number): string => value.toString().padStart(2, "0");

export const formatTimberbornSaveTimestamp = (date: Date): string =>
  `${twoDigit(date.getMonth() + 1)}/${twoDigit(date.getDate())}/${date.getFullYear()} ${twoDigit(date.getHours())}:${twoDigit(
    date.getMinutes(),
  )}:${twoDigit(date.getSeconds())}`;

export const isTimberbornSaveTimestamp = (value: JsonValue | undefined): boolean =>
  typeof value === "string" && timberbornSaveTimestampPattern.test(value);

const getPath = (value: JsonValue, path: string[]): JsonValue | undefined =>
  path.reduce<JsonValue | undefined>((current, key) => asObject(current)?.[key], value);

const viewOf = (buffer: Buffer): DataView => new DataView(buffer.buffer, buffer.byteOffset, buffer.byteLength);

const readUtf8 = (buffer: Buffer, offset: number, length: number): string => buffer.subarray(offset, offset + length).toString("utf8");

const findEndOfCentralDirectory = (bytes: Buffer): number => {
  let offset = bytes.length - 22;
  while (offset >= 0) {
    if (viewOf(bytes).getUint32(offset, true) === 0x06054b50) {
      return offset;
    }
    offset -= 1;
  }

  return fail("Could not find ZIP end-of-central-directory record.");
};

const readZip = (path: string): ZipEntry[] => {
  const bytes = readFileSync(path);
  const view = viewOf(bytes);
  const eocdOffset = findEndOfCentralDirectory(bytes);
  const entryCount = view.getUint16(eocdOffset + 10, true);
  const centralDirectoryOffset = view.getUint32(eocdOffset + 16, true);

  return Array.from({ length: entryCount }).reduce<{ entries: ZipEntry[]; offset: number }>(
    (state) => {
      if (view.getUint32(state.offset, true) !== 0x02014b50) {
        fail(`Invalid ZIP central directory signature at offset ${state.offset}.`);
      }

      const compressionMethod = view.getUint16(state.offset + 10, true);
      const compressedSize = view.getUint32(state.offset + 20, true);
      const uncompressedSize = view.getUint32(state.offset + 24, true);
      const fileNameLength = view.getUint16(state.offset + 28, true);
      const extraLength = view.getUint16(state.offset + 30, true);
      const commentLength = view.getUint16(state.offset + 32, true);
      const localHeaderOffset = view.getUint32(state.offset + 42, true);
      const name = readUtf8(bytes, state.offset + 46, fileNameLength);

      if (view.getUint32(localHeaderOffset, true) !== 0x04034b50) {
        fail(`Invalid ZIP local header signature for ${name}.`);
      }

      const localNameLength = view.getUint16(localHeaderOffset + 26, true);
      const localExtraLength = view.getUint16(localHeaderOffset + 28, true);
      const dataOffset = localHeaderOffset + 30 + localNameLength + localExtraLength;
      const compressedData = bytes.subarray(dataOffset, dataOffset + compressedSize);
      const data =
        compressionMethod === 0
          ? Buffer.from(compressedData)
          : compressionMethod === 8
            ? inflateRawSync(compressedData)
            : fail(`Unsupported ZIP compression method ${compressionMethod} for ${name}.`);

      if (data.length !== uncompressedSize) {
        fail(`Uncompressed size mismatch for ${name}: expected ${uncompressedSize}, got ${data.length}.`);
      }

      return {
        entries: [...state.entries, { compressedSize, compressionMethod, data, name, uncompressedSize }],
        offset: state.offset + 46 + fileNameLength + extraLength + commentLength,
      };
    },
    { entries: [], offset: centralDirectoryOffset },
  ).entries;
};

const crcTable = Array.from({ length: 256 }, (_, index) =>
  Array.from({ length: 8 }).reduce(
    (crc) => ((crc as number) & 1 ? 0xedb88320 ^ ((crc as number) >>> 1) : (crc as number) >>> 1),
    index,
  ) as number,
);

const crc32 = (data: Buffer): number =>
  data.reduce((crc, byte) => (crcTable[(crc ^ byte) & 0xff] ?? 0) ^ (crc >>> 8), 0xffffffff) ^ 0xffffffff;

const dosDateTime = (date: Date): { date: number; time: number } => ({
  date: ((date.getFullYear() - 1980) << 9) | ((date.getMonth() + 1) << 5) | date.getDate(),
  time: (date.getHours() << 11) | (date.getMinutes() << 5) | Math.floor(date.getSeconds() / 2),
});

const writeZip = (path: string, entries: ZipEntry[]): void => {
  const now = dosDateTime(new Date());
  const localRecords = entries.reduce<{ chunks: Buffer[]; central: Buffer[]; offset: number }>(
    (state, entry) => {
      const name = Buffer.from(entry.name, "utf8");
      const compressedData = deflateRawSync(entry.data);
      const checksum = crc32(entry.data) >>> 0;
      const localHeader = Buffer.alloc(30 + name.length);
      const centralHeader = Buffer.alloc(46 + name.length);

      localHeader.writeUInt32LE(0x04034b50, 0);
      localHeader.writeUInt16LE(20, 4);
      localHeader.writeUInt16LE(0x0800, 6);
      localHeader.writeUInt16LE(8, 8);
      localHeader.writeUInt16LE(now.time, 10);
      localHeader.writeUInt16LE(now.date, 12);
      localHeader.writeUInt32LE(checksum, 14);
      localHeader.writeUInt32LE(compressedData.length, 18);
      localHeader.writeUInt32LE(entry.data.length, 22);
      localHeader.writeUInt16LE(name.length, 26);
      localHeader.writeUInt16LE(0, 28);
      name.copy(localHeader, 30);

      centralHeader.writeUInt32LE(0x02014b50, 0);
      centralHeader.writeUInt16LE(20, 4);
      centralHeader.writeUInt16LE(20, 6);
      centralHeader.writeUInt16LE(0x0800, 8);
      centralHeader.writeUInt16LE(8, 10);
      centralHeader.writeUInt16LE(now.time, 12);
      centralHeader.writeUInt16LE(now.date, 14);
      centralHeader.writeUInt32LE(checksum, 16);
      centralHeader.writeUInt32LE(compressedData.length, 20);
      centralHeader.writeUInt32LE(entry.data.length, 24);
      centralHeader.writeUInt16LE(name.length, 28);
      centralHeader.writeUInt16LE(0, 30);
      centralHeader.writeUInt16LE(0, 32);
      centralHeader.writeUInt16LE(0, 34);
      centralHeader.writeUInt16LE(0, 36);
      centralHeader.writeUInt32LE(0, 38);
      centralHeader.writeUInt32LE(state.offset, 42);
      name.copy(centralHeader, 46);

      return {
        chunks: [...state.chunks, localHeader, compressedData],
        central: [...state.central, centralHeader],
        offset: state.offset + localHeader.length + compressedData.length,
      };
    },
    { central: [], chunks: [], offset: 0 },
  );
  const centralDirectory = Buffer.concat(localRecords.central);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  eocd.writeUInt16LE(entries.length, 8);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(centralDirectory.length, 12);
  eocd.writeUInt32LE(localRecords.offset, 16);
  eocd.writeUInt16LE(0, 20);

  writeFileSync(path, Buffer.concat([...localRecords.chunks, centralDirectory, eocd]));
};

const inspectArchive = (templatePath: string): ArchiveInspection => {
  const entries = readZip(templatePath);
  const jsonFiles = entries
    .filter((entry) => entry.name.endsWith(".json"))
    .reduce<Record<string, JsonValue>>((files, entry) => ({ ...files, [entry.name]: JSON.parse(entry.data.toString("utf8")) as JsonValue }), {});

  return { entries, jsonFiles };
};

const mapSizeOf = (world: JsonValue | undefined): { x: number | null; y: number | null } => ({
  x: asNumber(getPath(world ?? null, ["Singletons", "MapSize", "Size", "X"])),
  y: asNumber(getPath(world ?? null, ["Singletons", "MapSize", "Size", "Y"])),
});

const createLayoutRequests = (): EntityRequest[] => [
  ...[12, 13, 14, 15].map((x) => ({ category: "badwater-channel-source", coordinate: { x, y: 48, z: 2 }, template: "BadwaterSource" })),
  ...[31, 32, 33, 34].map((x) => ({ category: "water-channel-source", coordinate: { x, y: 48, z: 2 }, template: "WaterSource" })),
  ...[3, 5, 7, 9].flatMap((x) => [
    { category: "tree-pad", coordinate: { x, y: 45, z: 2 }, template: "Pine" },
    { category: "tree-pad", coordinate: { x, y: 43, z: 2 }, template: "Birch" },
    { category: "tree-pad", coordinate: { x, y: 41, z: 2 }, template: "Oak" },
  ]),
  ...[3, 5, 7, 9].map((x) => ({ category: "crop-pad", coordinate: { x, y: 5, z: 2 }, template: "Carrot" })),
  ...[
    { category: "wood-heavy-structure-pad", coordinate: { x: 21, y: 25, z: 2 }, template: "MediumWarehouse.Folktails" },
    { category: "mixed-material-structure-pad", coordinate: { x: 26, y: 25, z: 2 }, template: "LargePile.Folktails" },
    { category: "stored-water-pad", coordinate: { x: 38, y: 21, z: 2 }, template: "SmallTank.Folktails" },
    { category: "central-camera-lane", coordinate: { x: 24, y: 20, z: 2 }, template: "Path" },
    { category: "central-camera-lane", coordinate: { x: 24, y: 21, z: 2 }, template: "Path" },
    { category: "central-camera-lane", coordinate: { x: 24, y: 22, z: 2 }, template: "Path" },
  ],
];

const templateCandidatesByRequestTemplate: Record<string, string[]> = {
  Carrot: ["Carrot", "Potato", "Wheat", "Sunflower"],
  Path: ["Path", "Path.Folktails"],
};

const templateCandidatesFor = (template: string): string[] => templateCandidatesByRequestTemplate[template] ?? [template];

const countByCategory = (requests: EntityRequest[]): Record<string, number> =>
  requests.reduce<Record<string, number>>(
    (counts, request) => ({ ...counts, [request.category]: (counts[request.category] ?? 0) + 1 }),
    {},
  );

const coordinateKey = (coordinate: Coordinate): string => `${coordinate.x},${coordinate.y},${coordinate.z}`;

const entityCoordinate = (entity: JsonValue): Coordinate | null => {
  const coordinates = asObject(getPath(entity, ["Components", "BlockObject", "Coordinates"]));
  const x = asNumber(coordinates?.X);
  const y = asNumber(coordinates?.Y);
  const z = asNumber(coordinates?.Z);

  return x === null || y === null || z === null ? null : { x, y, z };
};

const entityTemplate = (entity: JsonValue): string | null => asString(asObject(entity)?.Template);

const plannedCoordinateBlocker = (world: JsonValue): string => {
  const terrainVoxels = getPath(world, ["Singletons", "TerrainMap", "Voxels", "Array"]);

  return typeof terrainVoxels === "string"
    ? "planned coordinate requires matching terrain/channel/support mutation, but this generator leaves TerrainMap.Voxels.Array unchanged; using existing template-supported coordinates when available"
    : "planned coordinate requires terrain/channel/support validation, but Singletons.TerrainMap.Voxels.Array is missing or not a string";
};

const existingSupportedPlacements = (entities: JsonValue[]): Record<string, EntityRequest[]> =>
  entities.reduce<Record<string, EntityRequest[]>>((placements, entity) => {
    const template = entityTemplate(entity);
    const coordinate = entityCoordinate(entity);
    if (!template || !coordinate) {
      return placements;
    }

    return {
      ...placements,
      [template]: [...(placements[template] ?? []), { category: "template-supported-checkpoint", coordinate, template }],
    };
  }, {});

const takeSupportedPlacement = (
  supportedPlacements: Record<string, EntityRequest[]>,
  nextSupportedIndexByTemplate: Record<string, number>,
  template: string,
): { nextSupportedIndexByTemplate: Record<string, number>; supportedPlacement: EntityRequest | null } =>
  templateCandidatesFor(template).reduce<{ nextSupportedIndexByTemplate: Record<string, number>; supportedPlacement: EntityRequest | null }>(
    (state, candidate) => {
      if (state.supportedPlacement) {
        return state;
      }

      const supportedForTemplate = supportedPlacements[candidate] ?? [];
      const nextSupportedIndex = state.nextSupportedIndexByTemplate[candidate] ?? 0;
      const supportedPlacement = supportedForTemplate[nextSupportedIndex] ?? null;

      return supportedPlacement
        ? {
            nextSupportedIndexByTemplate: {
              ...state.nextSupportedIndexByTemplate,
              [candidate]: nextSupportedIndex + 1,
            },
            supportedPlacement,
          }
        : state;
    },
    { nextSupportedIndexByTemplate, supportedPlacement: null },
  );

const supportedCandidateCount = (supportedPlacements: Record<string, EntityRequest[]>, template: string): number =>
  templateCandidatesFor(template).reduce((count, candidate) => count + (supportedPlacements[candidate]?.length ?? 0), 0);

const requestTemplateLabel = (template: string): string => templateCandidatesFor(template).join(" or ");

const sourceMaterialClassByCategory: Record<string, MaterialClass> = {
  "badwater-channel-source": "badwater",
  "central-camera-lane": "infrastructure",
  "crop-pad": "crop",
  "mixed-material-structure-pad": "storage",
  "stored-water-pad": "storage",
  "tree-pad": "tree",
  "water-channel-source": "water",
  "wood-heavy-structure-pad": "building",
};

const cellMaterialClassFor = (request: EntityRequest): MaterialClass =>
  ["mixed-material-structure-pad", "stored-water-pad"].includes(request.category) ? "building" : sourceMaterialClassByCategory[request.category] ?? "unknown";

const expectedBandFor = (profile: MaterialFieldProfile): ScenarioCheckpoint["expectedPackedCellBand"] => ({
  flammability: profile.flammability,
  fuel: profile.fuel,
  heatLoss: profile.heatLoss,
  terrain: profile.terrain,
  water: profile.water,
});

const checkpointForGeneratedEntity = (request: EntityRequest, categoryOrdinal: number): ScenarioCheckpoint => {
  const expectedSourceMaterialClass = sourceMaterialClassByCategory[request.category] ?? "unknown";
  const expectedCellMaterialClass = cellMaterialClassFor(request);
  const cellProfile = lookupMaterialProfile(expectedCellMaterialClass);

  return {
    category: request.category,
    companionField: {
      ashQuality: cellProfile.ashQuality,
      burnCapacity: cellProfile.burnCapacity,
      contaminationBehavior: cellProfile.contaminationBehavior,
      consequenceTargetKind: cellProfile.consequenceTargetKind,
      resourcePolicy: cellProfile.resourcePolicy,
    },
    coordinate: request.coordinate,
    expectedCellMaterialClass,
    expectedPackedCellBand: expectedBandFor(cellProfile),
    expectedSourceMaterialClass,
    id: `${request.category}-${categoryOrdinal}`,
    template: request.template,
  };
};

const staticFieldCheckpoints = (): ScenarioCheckpoint[] => {
  const terrainProfile = lookupMaterialProfile("terrain");
  const emptyProfile = lookupMaterialProfile("empty");

  return [
    {
      category: "terrain-control",
      companionField: {
        ashQuality: terrainProfile.ashQuality,
        burnCapacity: terrainProfile.burnCapacity,
        contaminationBehavior: terrainProfile.contaminationBehavior,
        consequenceTargetKind: terrainProfile.consequenceTargetKind,
        resourcePolicy: terrainProfile.resourcePolicy,
      },
      coordinate: { x: 1, y: 1, z: 2 },
      expectedCellMaterialClass: "terrain",
      expectedPackedCellBand: expectedBandFor(terrainProfile),
      expectedSourceMaterialClass: "terrain",
      id: "terrain-control-1",
      template: null,
    },
    {
      category: "empty-control",
      companionField: {
        ashQuality: emptyProfile.ashQuality,
        burnCapacity: emptyProfile.burnCapacity,
        contaminationBehavior: emptyProfile.contaminationBehavior,
        consequenceTargetKind: emptyProfile.consequenceTargetKind,
        resourcePolicy: emptyProfile.resourcePolicy,
      },
      coordinate: { x: 1, y: 1, z: 8 },
      expectedCellMaterialClass: "empty",
      expectedPackedCellBand: expectedBandFor(emptyProfile),
      expectedSourceMaterialClass: "empty",
      id: "empty-control-1",
      template: null,
    },
  ];
};

export const buildFieldCheckpoints = (generated: EntityRequest[]): ScenarioCheckpoint[] => [
  ...staticFieldCheckpoints(),
  ...generated.reduce<{ checkpoints: ScenarioCheckpoint[]; countsByCategory: Record<string, number> }>(
    (state, request) => {
      const nextOrdinal = (state.countsByCategory[request.category] ?? 0) + 1;

      return {
        checkpoints: [...state.checkpoints, checkpointForGeneratedEntity(request, nextOrdinal)],
        countsByCategory: {
          ...state.countsByCategory,
          [request.category]: nextOrdinal,
        },
      };
    },
    { checkpoints: [], countsByCategory: {} },
  ).checkpoints,
];

export const mutateWorldEntities = (world: JsonValue): { blockers: EntityPlacement[]; generated: EntityRequest[]; nextWorld: JsonValue } => {
  const nextWorld = cloneJson(world);
  const entities = asArray(asObject(nextWorld)?.Entities);
  if (!entities) {
    return {
      blockers: createLayoutRequests().map((request) => ({ ...request, blockedReason: "world.json path Entities is not an array" })),
      generated: [],
      nextWorld,
    };
  }

  const size = mapSizeOf(nextWorld);
  const planned = createLayoutRequests();
  if ((size.x ?? 0) < 50 || (size.y ?? 0) < 50) {
    return {
      blockers: planned.map((request) => ({ ...request, blockedReason: `template map is ${size.x ?? "unknown"}x${size.y ?? "unknown"}, smaller than 50x50` })),
      generated: [],
      nextWorld,
    };
  }

  const supportedPlacements = existingSupportedPlacements(entities);
  const coordinateBlocker = plannedCoordinateBlocker(nextWorld);
  const placements = planned.reduce<{ blockers: EntityPlacement[]; generated: EntityRequest[]; nextEntities: JsonValue[]; nextSupportedIndexByTemplate: Record<string, number> }>(
    (state, request) => {
      const placement = takeSupportedPlacement(supportedPlacements, state.nextSupportedIndexByTemplate, request.template);
      const supportedPlacement = placement.supportedPlacement;
      const key = coordinateKey(request.coordinate);
      if (!supportedPlacement) {
        const supportedCount = supportedCandidateCount(supportedPlacements, request.template);
        const templateLabel = requestTemplateLabel(request.template);

        return {
          ...state,
          blockers: [
            ...state.blockers,
            {
              ...request,
              blockedReason:
                supportedCount === 0
                  ? `template entity ${templateLabel} was not found in world.json Entities with valid BlockObject coordinates`
                  : `only ${supportedCount} existing template-supported ${templateLabel} checkpoint(s) were found; planned coordinate ${key} is blocked because ${coordinateBlocker}`,
            },
          ],
        };
      }

      return {
        ...state,
        generated: [...state.generated, { ...request, coordinate: supportedPlacement.coordinate, template: supportedPlacement.template }],
        nextSupportedIndexByTemplate: placement.nextSupportedIndexByTemplate,
      };
    },
    { blockers: [], generated: [], nextEntities: entities, nextSupportedIndexByTemplate: {} },
  );

  asObject(nextWorld)!.Entities = placements.nextEntities;

  return { blockers: placements.blockers, generated: placements.generated, nextWorld };
};

export const buildSaveMetadataShapeBlockers = (metadata: JsonValue | undefined): string[] => {
  const object = asObject(metadata);
  const timestamp = object?.Timestamp;
  const cycle = object?.Cycle;
  const day = object?.Day;
  const mods = object?.Mods;

  return [
    !object ? "save_metadata.json root is missing or not an object" : null,
    object && !isTimberbornSaveTimestamp(timestamp)
      ? "save_metadata.json Timestamp must use Timberborn save format MM/dd/yyyy HH:mm:ss"
      : null,
    object && typeof cycle !== "number" ? "save_metadata.json Cycle must be a number" : null,
    object && typeof day !== "number" ? "save_metadata.json Day must be a number" : null,
    object && !Array.isArray(mods) ? "save_metadata.json Mods must be an array" : null,
  ].filter((message): message is string => message !== null);
};

const buildSchemaBlockers = (
  inspection: ArchiveInspection,
  world: JsonValue | undefined,
  metadata: JsonValue | undefined,
  entityBlockers: EntityPlacement[],
): string[] => {
  const entries = new Set(inspection.entries.map((entry) => entry.name));
  const terrainVoxels = getPath(world ?? null, ["Singletons", "TerrainMap", "Voxels", "Array"]);
  const entities = asArray(getPath(world ?? null, ["Entities"]));

  return [
    !entries.has("world.json") ? "archive member world.json is missing" : null,
    !entries.has("save_metadata.json") ? "archive member save_metadata.json is missing" : null,
    typeof terrainVoxels === "string"
      ? "Singletons.TerrainMap.Voxels.Array is a space-delimited voxel string; generator does not carve planned terrain/channels and instead emits existing template-supported checkpoint coordinates when available"
      : "Singletons.TerrainMap.Voxels.Array is missing or not a string; terrain layout mutation and entity placement are blocked",
    entities ? null : "world.json path Entities is missing or not an array; entity placement is blocked",
    "Storage inventory contents are not mutated because the inspected storage prototypes are unfinished construction sites without inventory payloads",
    "Crop pads depend on crop entity prototypes in the template; missing prototypes are recorded per placement",
    ...buildSaveMetadataShapeBlockers(metadata),
    ...entityBlockers.map(
      (blocker) =>
        `${blocker.category} ${blocker.template} at (${blocker.coordinate.x},${blocker.coordinate.y},${blocker.coordinate.z}): ${blocker.blockedReason}`,
    ),
  ].filter((message): message is string => message !== null);
};

export const updateMetadata = (metadata: JsonValue | undefined, generatedAt: Date): JsonValue | undefined => {
  if (!metadata) {
    return undefined;
  }

  const nextMetadata = cloneJson(metadata);
  const object = asObject(nextMetadata);
  if (object) {
    object.Timestamp = formatTimberbornSaveTimestamp(generatedAt);
  }

  return nextMetadata;
};

const replaceEntry = (entries: ZipEntry[], name: string, data: Buffer): ZipEntry[] =>
  entries.map((entry) => (entry.name === name ? { ...entry, data, uncompressedSize: data.length } : entry));

const entityAt = (entities: JsonValue[], coordinate: Coordinate): JsonObject | null =>
  (entities.find((entity) => {
    const existingCoordinate = entityCoordinate(entity);
    return existingCoordinate ? coordinateKey(existingCoordinate) === coordinateKey(coordinate) : false;
  }) ?? null) as JsonObject | null;

const collectStringProperties = (value: JsonValue, keys: Set<string>): string[] => {
  if (Array.isArray(value)) {
    return value.flatMap((item) => collectStringProperties(item, keys));
  }
  const object = asObject(value);
  if (!object) {
    return [];
  }

  return Object.entries(object).flatMap(([key, child]) => [
    ...(keys.has(key) && typeof child === "string" ? [child] : []),
    ...collectStringProperties(child, keys),
  ]);
};

const describeFlowEvidence = (generated: EntityRequest[], category: string): string => {
  const coordinates = generated.filter((request) => request.category === category).map((request) => request.coordinate);
  if (coordinates.length < 2) {
    return `${category} has ${coordinates.length} checkpoint(s); static archive inspection cannot prove a channel or flow direction.`;
  }

  const xValues = coordinates.map((coordinate) => coordinate.x);
  const yValues = coordinates.map((coordinate) => coordinate.y);
  const zValues = coordinates.map((coordinate) => coordinate.z);

  return `${category} checkpoints span x=${Math.min(...xValues)}..${Math.max(...xValues)}, y=${Math.min(...yValues)}..${Math.max(...yValues)}, z=${Math.min(...zValues)}..${Math.max(...zValues)}; live QA must confirm actual north-to-south flow.`;
};

const describeStorageInventoryEvidence = (world: JsonValue | undefined, generated: EntityRequest[]): string => {
  const entities = asArray(getPath(world ?? null, ["Entities"])) ?? [];
  const storageEntities = generated
    .filter((request) => ["mixed-material-structure-pad", "stored-water-pad", "wood-heavy-structure-pad"].includes(request.category))
    .map((request) => entityAt(entities, request.coordinate))
    .filter((entity): entity is JsonObject => entity !== null);
  const goods = Array.from(
    new Set(storageEntities.flatMap((entity) => collectStringProperties(entity, new Set(["AllowedGood", "CurrentGood", "Good", "GoodId"])))),
  ).sort();

  return goods.length > 0
    ? `storage/structure checkpoints reference goods: ${goods.join(", ")}`
    : "storage/structure checkpoints expose no inventory goods in static archive inspection; live QA or a purpose-built stocked template must prove contents.";
};

const buildEvidence = (
  world: JsonValue | undefined,
  generated: EntityRequest[],
): { badwaterFlow: string; storageInventory: string; waterFlow: string } => ({
  badwaterFlow: describeFlowEvidence(generated, "badwater-channel-source"),
  storageInventory: describeStorageInventoryEvidence(world, generated),
  waterFlow: describeFlowEvidence(generated, "water-channel-source"),
});

const buildManifest = (
  options: Options,
  inspection: ArchiveInspection,
  generatedAt: string,
  archivePath: string,
  manifestPath: string,
  generated: EntityRequest[],
  blockedPlacements: EntityPlacement[],
  schemaBlockers: string[],
): Manifest => {
  const world = inspection.jsonFiles["world.json"];
  const mapSize = mapSizeOf(world);

  return {
    generatedAt,
    generator: {
      command: ["bun", "scripts/generate-wildfire-scenario-save.ts", ...Bun.argv.slice(2)].join(" "),
      mutateEntities: options.mutateEntities,
      name: options.name,
      tool: generatorTool,
      version: generatorVersion,
    },
    output: {
      archivePath,
      manifestPath,
    },
    plan: {
      expectedEntityCountsByCategory: countByCategory(createLayoutRequests()),
      layout: {
        baseHeight: 2,
        region: "x=0..49, y=0..49 of the copied template",
        size: { x: 50, y: 50 },
        xBands: [
          "x=0..10 land/tree/crop test band",
          "x=11..17 badwater channel",
          "x=18..29 central structure/camera band",
          "x=30..36 water channel",
          "x=37..49 land/storage/suppression band",
        ],
      },
    },
    result: {
      blockedPlacements,
      evidence: buildEvidence(world, generated),
      fieldCheckpoints: buildFieldCheckpoints(generated),
      generatedEntityCountsByCategory: countByCategory(generated),
      generatedEntities: generated,
      schemaBlockers,
    },
    template: {
      entries: inspection.entries.map((entry) => entry.name),
      jsonFiles: Object.keys(inspection.jsonFiles),
      mapSize,
      path: options.templatePath ?? "",
      version: inspection.entries.find((entry) => entry.name === "version.txt")?.data.toString("utf8").trim() ?? null,
    },
    validationTargets: [
      "TWF-119 should load the generated archive in Timberborn before accepting it as a real save fixture.",
      "Confirm the output uses the copied template and not a direct user-save path.",
      "Inspect manifest result.schemaBlockers before relying on terrain channels, crop pads, or storage contents.",
      "If live loading succeeds, capture screenshot framing for water channel, badwater channel, central structure pads, tree pads, and stored-water pad.",
    ],
  };
};

const isSameOrInside = (path: string, parent: string): boolean => {
  const child = resolve(path);
  const root = resolve(parent);
  const diff = relative(root, child);

  return diff === "" || (!diff.startsWith("..") && !diff.startsWith("/") && diff !== "..");
};

const isChildPath = (path: string, parent: string): boolean => {
  const diff = relative(resolve(parent), resolve(path));

  return diff !== "" && !diff.startsWith("..") && !diff.startsWith("/") && diff !== "..";
};

const assertPathInside = (path: string, parent: string, label: string): string => {
  const resolvedPath = resolve(path);
  if (!isChildPath(resolvedPath, parent)) {
    fail(`${label} must stay inside the output directory. Refusing path: ${resolvedPath}`);
  }

  return resolvedPath;
};

const assertNoExistingSymlink = (path: string, label: string): void => {
  if (existsSync(path) && lstatSync(path).isSymbolicLink()) {
    fail(`${label} must not be a symbolic link: ${path}`);
  }
};

const nearestExistingParent = (path: string): string => {
  let current = resolve(path);
  while (!existsSync(current)) {
    const parent = dirname(current);
    if (parent === current) {
      fail(`Could not find an existing parent directory for ${path}.`);
    }
    current = parent;
  }

  return current;
};

const existingAncestorsFrom = (root: string, path: string): string[] => {
  const resolvedRoot = resolve(root);
  const resolvedPath = resolve(path);
  const segments = relative(resolvedRoot, resolvedPath)
    .split("/")
    .filter((segment) => segment.length > 0);

  return segments.reduce<string[]>(
    (ancestors, segment) => {
      const next = join(ancestors.at(-1) ?? resolvedRoot, segment);
      return existsSync(next) ? [...ancestors, next] : ancestors;
    },
    [resolvedRoot],
  );
};

const assertExistingDirectory = (path: string, label: string): void => {
  if (!existsSync(path)) {
    return;
  }
  if (!lstatSync(path).isDirectory()) {
    fail(`${label} exists but is not a directory: ${path}`);
  }
};

const assertNoSymlinkedExistingDirectory = (path: string): void => {
  assertNoExistingSymlink(path, "Output folder");
  assertExistingDirectory(path, "Output path");
};

const isClearlyGeneratedScenarioOutputDir = (outputDir: string): boolean => {
  const normalized = resolve(outputDir);
  const segments = normalized.split("/");
  const finalSegment = segments.at(-1) ?? "";

  return isChildPath(normalized, generatedScenariosRoot) && finalSegment.length > 0;
};

const validateOutputDirSafety = (outputDir: string): string => {
  const resolvedOutputDir = resolve(outputDir);
  const dangerousRoots = [
    resolve("/"),
    resolve(home),
    resolve(home, "Documents"),
    resolve(home, "Documents", "Timberborn"),
    resolve(home, "Documents", "Timberborn", "ExperimentalSaves"),
    resolve(home, "Documents", "Timberborn", "Maps"),
  ];
  const matchingDangerousRoot = dangerousRoots.find((root) => resolvedOutputDir === root);
  if (matchingDangerousRoot) {
    fail(`Refusing dangerous output directory: ${matchingDangerousRoot}`);
  }
  if (isSameOrInside(resolvedOutputDir, resolve(home, "Documents", "Timberborn"))) {
    fail(`Refusing to write generated scenario output under Documents/Timberborn save roots: ${resolvedOutputDir}`);
  }
  if (!isClearlyGeneratedScenarioOutputDir(resolvedOutputDir)) {
    fail(
      `Refusing output directory that is not clearly a generated Wildfire scenario folder: ${resolvedOutputDir}. Use a folder under ${join(
        generatedScenariosRoot,
        "<scenario-name>",
      )}.`,
    );
  }

  return resolvedOutputDir;
};

const assertRealParentChainInsideGeneratedRoot = (outputDir: string): void => {
  if (!existsSync(generatedScenariosRoot)) {
    const rootParent = nearestExistingParent(dirname(generatedScenariosRoot));
    assertNoExistingSymlink(rootParent, "Generated scenario root parent");
    assertExistingDirectory(rootParent, "Generated scenario root parent");
    const realRootParent = realpathSync(rootParent);
    if (realRootParent !== resolve(rootParent)) {
      fail(`Generated scenario root parent must not resolve through a symlink: ${rootParent} -> ${realRootParent}`);
    }
    mkdirSync(generatedScenariosRoot, { recursive: true });
  }

  assertNoExistingSymlink(generatedScenariosRoot, "Generated scenario root");
  assertExistingDirectory(generatedScenariosRoot, "Generated scenario root");
  const realGeneratedRoot = realpathSync(generatedScenariosRoot);
  if (realGeneratedRoot !== resolve(generatedScenariosRoot)) {
    fail(`Generated scenario root must not be a symbolic link: ${generatedScenariosRoot} -> ${realGeneratedRoot}`);
  }

  const existingAncestors = existingAncestorsFrom(generatedScenariosRoot, outputDir);
  existingAncestors.forEach((ancestor) => {
    assertNoExistingSymlink(ancestor, "Output ancestor");
    assertExistingDirectory(ancestor, "Output ancestor");
    const realAncestor = realpathSync(ancestor);
    if (!isSameOrInside(realAncestor, realGeneratedRoot)) {
      fail(`Output ancestor escapes generated scenario root: ${ancestor} -> ${realAncestor}`);
    }
  });

  const nearestParent = nearestExistingParent(dirname(outputDir));
  const realNearestParent = realpathSync(nearestParent);
  if (!isSameOrInside(realNearestParent, realGeneratedRoot)) {
    fail(`Output parent escapes generated scenario root: ${nearestParent} -> ${realNearestParent}`);
  }
};

const readManifestMarker = (manifestPath: string): string | null => {
  if (!existsSync(manifestPath)) {
    return null;
  }

  try {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as JsonValue;
    return asString(getPath(manifest, ["generator", "tool"]));
  } catch {
    return fail(`Refusing --overwrite because ${manifestPath} is not readable generated-scenario JSON.`);
  }
};

const assertExistingOutputIsGeneratedByThisTool = (outputDir: string, manifestPath: string): void => {
  if (!existsSync(outputDir)) {
    return;
  }
  if (!existsSync(manifestPath)) {
    fail(`Refusing --overwrite because no prior ${manifestFileName} marker exists in ${outputDir}.`);
  }

  const marker = readManifestMarker(manifestPath);
  if (marker !== generatorTool) {
    fail(`Refusing --overwrite because ${manifestPath} is not marked as generated by ${generatorTool}.`);
  }
};

const outputPathsFor = (options: Options): { archivePath: string; manifestPath: string; outputDir: string } => {
  const outputDir = validateOutputDirSafety(options.outputDir);
  const archivePath = assertPathInside(resolve(outputDir, `${options.name}.timber`), outputDir, "Archive path");
  const manifestPath = assertPathInside(resolve(outputDir, manifestFileName), outputDir, "Manifest path");

  return { archivePath, manifestPath, outputDir };
};

const assertFinalPathConfinement = (outputDir: string, archivePath: string, manifestPath: string): void => {
  const realGeneratedRoot = realpathSync(generatedScenariosRoot);
  const realOutputDir = realpathSync(outputDir);
  if (!isSameOrInside(realOutputDir, realGeneratedRoot)) {
    fail(`Output folder escapes generated scenario root after creation: ${outputDir} -> ${realOutputDir}`);
  }
  assertPathInside(archivePath, outputDir, "Archive path");
  assertPathInside(manifestPath, outputDir, "Manifest path");
};

const prepareOutputDir = (outputDir: string, archivePath: string, manifestPath: string, overwrite: boolean): void => {
  assertRealParentChainInsideGeneratedRoot(outputDir);
  assertNoExistingSymlink(outputDir, "Output folder");
  assertNoExistingSymlink(manifestPath, "Manifest path");
  assertNoSymlinkedExistingDirectory(outputDir);

  if (existsSync(outputDir) && !overwrite) {
    fail(`Output folder already exists. Use --overwrite to replace it: ${outputDir}`);
  }
  if (existsSync(outputDir)) {
    assertExistingOutputIsGeneratedByThisTool(outputDir, manifestPath);
    rmSync(outputDir, { recursive: true });
  }

  mkdirSync(outputDir, { recursive: true });
  assertFinalPathConfinement(outputDir, archivePath, manifestPath);
};

const run = (): void => {
  const options = parseArgs(Bun.argv.slice(2));
  if (options.help) {
    console.log(usage);
    return;
  }
  const templatePath = options.templatePath ?? fail("--template is required.");
  if (!existsSync(templatePath)) {
    fail(`Template archive does not exist: ${templatePath}`);
  }

  const generatedAtDate = new Date();
  const generatedAt = generatedAtDate.toISOString();
  const paths = outputPathsFor(options);
  const inspection = inspectArchive(templatePath);
  const world = inspection.jsonFiles["world.json"];
  const mutation = options.mutateEntities && world ? mutateWorldEntities(world) : { blockers: [], generated: [], nextWorld: world };
  const metadata = updateMetadata(inspection.jsonFiles["save_metadata.json"], generatedAtDate);
  const schemaBlockers = buildSchemaBlockers(inspection, world, metadata, mutation.blockers);
  const manifest = buildManifest(options, inspection, generatedAt, paths.archivePath, paths.manifestPath, mutation.generated, mutation.blockers, schemaBlockers);

  log(`template=${templatePath}`);
  log(`output_dir=${paths.outputDir}`);
  log(`archive_entries=${inspection.entries.map((entry) => entry.name).join(",")}`);
  log(`json_files=${Object.keys(inspection.jsonFiles).join(",")}`);
  log(`map_size=${manifest.template.mapSize.x ?? "unknown"}x${manifest.template.mapSize.y ?? "unknown"}`);
  log(`planned_counts=${JSON.stringify(manifest.plan.expectedEntityCountsByCategory)}`);
  log(`generated_counts=${JSON.stringify(manifest.result.generatedEntityCountsByCategory)}`);
  log(`schema_blockers=${schemaBlockers.length}`);

  if (options.dryRun) {
    log(`dry_run=true would_write_archive=${paths.archivePath}`);
    log(`dry_run=true would_write_manifest=${paths.manifestPath}`);
    console.log(JSON.stringify(manifest, null, 2));
    return;
  }

  prepareOutputDir(paths.outputDir, paths.archivePath, paths.manifestPath, options.overwrite);

  const entriesWithWorld =
    world && mutation.nextWorld
      ? replaceEntry(inspection.entries, "world.json", Buffer.from(JSON.stringify(mutation.nextWorld), "utf8"))
      : inspection.entries;
  const entriesWithMetadata = metadata
    ? replaceEntry(entriesWithWorld, "save_metadata.json", Buffer.from(JSON.stringify(metadata), "utf8"))
    : entriesWithWorld;

  writeZip(paths.archivePath, entriesWithMetadata);
  writeFileSync(paths.manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  log(`wrote_archive=${paths.archivePath}`);
  log(`wrote_manifest=${paths.manifestPath}`);
};

if (import.meta.main) {
  try {
    run();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
